### ISSUE TITLE
Browserify is only triggered if .browserify.js file is different.

### ISSUE THREAD

**Issue by rikthevik** [j0hnsmith/django-pipeline-browserify#13]
If you modify a file imported from require(), browserify is not called.

**Comment by rikthevik** [comment]
Looks like @furious-luke has a PR up.  Any thoughts on that?

**Comment by natevw** [comment]
If https://github.com/j0hnsmith/django-pipeline-browserify/pull/5 is the PR referred to, looks like that has been merged in. Is this still an issue?

**Comment by j0hnsmith** [comment]
This should be fixed, closing. Reopen if still a problem.
