### ISSUE TITLE
Suggestion add some note about BROWSERIFY_BINARY

### ISSUE THREAD

**Issue by ivictbor** [j0hnsmith/django-pipeline-browserify#17]
Hi. Thanks for project.

Default value of `BROWSERIFY_BINARY`  is
```
            pipeline_settings.get('BROWSERIFY_BINARY', '/usr/bin/env browserify'),
```
Which will not work on Windows. So may be it is good idea to mention about `BROWSERIFY_BINARY` option in readme.

**Comment by natevw** [comment]
Actually, this makes me realize an issue with #18 in that the default `BROWSERIFY_BINARY` will probably no longer work with the way I'm handling the commands :-/

Seems the solution to both the issue on Windows and the one I introduced would be to simply use 'browserify' as the default? It has to be in the PATH anyway for `env` to find it, so I don't see any advantage in the indirection, and as you've found there's downsides for cross-platform compatibility.
