### ISSUE TITLE
Command Compiles Incorrectly with Presets

### ISSUE THREAD

**Issue by djskripta** [j0hnsmith/django-pipeline-browserify#22]
When i set my `BROWSERIFY_ARGUMENTS` to include the `es2015` and `react` presets as described in the docs, the command compiles like this:
```
browserify -t [babelify --presets [es2015 react]] --list *****\static\***\js\app.browserify.js
```

The intended command is:
```
browserify -t [babelify --presets [es2015 react] ****\static\***\js\app.browserify.js] --list
```

I may just end up forking this and making my own implementation

**Comment by djskripta** [comment]
See fork:
https://github.com/djskripta/django-pipeline-browserify

**Comment by djskripta** [comment]
Turns out this was an issue with directory structure and where my browserify and es2015 preset was saved to. Still haven't resolved it, but im pretty sure it's not an issue with this library

**Comment by natevw** [comment]
Thanks for following up, and feel free to re-open if need be!
